### ISSUE TITLE
技术控你好。。。

### ISSUE THREAD

**Issue by sgysz** [Slahser/slahser.github.io#1]

**Comment by sgysz** [comment]
很荣幸拜读您的k8s实验文档，calico导致DNS起不来的原因是calicoctl版本问题，新版本不支持calicoctl add的形式，更换老版本即可。

**Comment by Slahser** [comment]
我这边症状是dns pod 正常启动，但是服务发现不奏效，我觉得是几个可能，但是因为我有拓扑图跟ingress 要做，所以姑且先用weave 

1. 可能是你说的版本问题，目前我用的是1.6
2. 大可能是文档中后续的Configuere  Kubernetes 那步我没做导致的，也就是配置kubelet 启动参数那一步。kubeadm 方式可以手动在10-kubeadm 那个位置修改
3.再不济不用容器内的方式也能解决掉这块。

还是看上了实体机器的压测结果，上一次压测在虚拟机内，走的都是宿主机的NAT ，我想结果不是很准

**Comment by Slahser** [comment]
升级到kubernetes 1.5.1 问题居然不存在了...我用的是docker中独立的etcd那个calico配置文件.

关闭issue了.
